# Generated by Django 4.0.4 on 2022-08-18 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название настройки')),
                ('conflicts', models.ManyToManyField(null=True, to='tests.testsetting', verbose_name='Конфликтующие настройки')),
            ],
            options={
                'verbose_name': 'Доступная настройка теста',
                'verbose_name_plural': 'Доступные настройки для тестов',
            },
        ),
        migrations.AlterModelOptions(
            name='answertoquestion',
            options={'verbose_name': 'Ответ пользователя', 'verbose_name_plural': 'Ответы пользователей'},
        ),
        migrations.AlterModelOptions(
            name='passedtest',
            options={'verbose_name': 'Пройденный тест', 'verbose_name_plural': 'Пройденные тесты'},
        ),
        migrations.AlterField(
            model_name='answertoquestion',
            name='open_answer',
            field=models.TextField(blank=True, verbose_name='Открытый ответ'),
        ),
        migrations.AlterField(
            model_name='answertoquestion',
            name='selected_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_answers', to='tests.variantforquestion', verbose_name='Выбранный ответ'),
        ),
        migrations.CreateModel(
            name='TestTimerSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('timer_value', models.DurationField(verbose_name='Длительность')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timer_values', to='tests.testsetting', verbose_name='Настройка')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timer_settings', to='tests.test', unique=True, verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Значение настройки Таймера',
                'verbose_name_plural': 'Значения настройки Таймера',
            },
        ),
        migrations.CreateModel(
            name='TestAvailabilityTimeRangeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('start_time', models.DateTimeField(verbose_name='Время начало доступа')),
                ('end_time', models.DateTimeField(verbose_name='Время конца доступа')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_time_range_values', to='tests.testsetting', verbose_name='Настройка')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_time_range_settings', to='tests.test', unique=True, verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Значение настройки Доступность по времени',
                'verbose_name_plural': 'Значения настройки Доступность по времени',
            },
        ),
    ]
