# Generated by Django 4.0.4 on 2022-08-18 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_testsetting_alter_answertoquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testavailabilitytimerangesetting',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability_time_range_settings', to='tests.test', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='testtimersetting',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timer_settings', to='tests.test', verbose_name='Тест'),
        ),
    ]
