# Generated by Django 4.0.4 on 2022-08-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_alter_testavailabilitytimerangesetting_test_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testsetting',
            options={'verbose_name': 'Настройка теста', 'verbose_name_plural': 'Настройки для тестов'},
        ),
        migrations.AlterField(
            model_name='testsetting',
            name='conflicts',
            field=models.ManyToManyField(blank=True, null=True, to='tests.testsetting', verbose_name='Конфликтующие настройки'),
        ),
    ]
