# Generated by Django 4.0.4 on 2022-08-18 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_alter_testsetting_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testtimersetting',
            options={'verbose_name': 'Значение настройки Таймера', 'verbose_name_plural': 'Значения настройек Таймера'},
        ),
        migrations.CreateModel(
            name='QuestionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название настройки')),
                ('conflicts', models.ManyToManyField(blank=True, null=True, to='tests.questionsetting', verbose_name='Конфликтующие настройки')),
            ],
            options={
                'verbose_name': 'Настройка вопроса',
                'verbose_name_plural': 'Настройки для вопросов',
            },
        ),
        migrations.CreateModel(
            name='QuestionPointSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('point', models.PositiveIntegerField(verbose_name='Кол-во баллов за этот вопрос')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='point_settings', to='tests.question', verbose_name='Вопрос')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_values', to='tests.questionsetting', verbose_name='Настройка')),
            ],
            options={
                'verbose_name': 'Значение настройки Кол-во баллов',
                'verbose_name_plural': 'Значения настройки Кол-во баллов',
            },
        ),
    ]
