# Generated by Django 4.0.4 on 2022-08-19 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_alter_testtimersetting_options_questionsetting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answertoquestion',
            name='open_answer',
        ),
        migrations.RemoveField(
            model_name='answertoquestion',
            name='selected_variant',
        ),
        migrations.CreateModel(
            name='SelectedVariantAnswerToQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('answer_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_variants', to='tests.answertoquestion', verbose_name='Ответ пользователя')),
                ('value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_answers', to='tests.variantforquestion', verbose_name='Выбранный ответ')),
            ],
            options={
                'verbose_name': 'Ответ пользователя на закрытый вопрос',
                'verbose_name_plural': 'Ответы пользователей на закрытые вопросы',
            },
        ),
        migrations.CreateModel(
            name='PointAnswerToQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('point', models.FloatField(verbose_name='Набранное кол-во баллов')),
                ('answer_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='point', to='tests.answertoquestion', verbose_name='Ответ пользователя')),
            ],
            options={
                'verbose_name': 'Балл за ответ пользователя',
                'verbose_name_plural': 'Баллы за ответы пользователей',
            },
        ),
        migrations.CreateModel(
            name='OpenAsnwerToQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('value', models.TextField(blank=True, verbose_name='Введенный ответ')),
                ('answer_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_answer', to='tests.answertoquestion', verbose_name='Ответ пользователя')),
            ],
            options={
                'verbose_name': 'Ответ пользователя на открытый вопрос',
                'verbose_name_plural': 'Ответы пользователей на открытые вопросы',
            },
        ),
    ]
