# Generated by Django 4.0.4 on 2022-08-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_remove_answertoquestion_open_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsetting',
            name='conflicts',
            field=models.ManyToManyField(blank=True, to='tests.questionsetting', verbose_name='Конфликтующие настройки'),
        ),
        migrations.AlterField(
            model_name='testsetting',
            name='conflicts',
            field=models.ManyToManyField(blank=True, to='tests.testsetting', verbose_name='Конфликтующие настройки'),
        ),
    ]
