# Generated by Django 4.1 on 2022-08-19 21:04

from django.db import migrations

def create_settings(apps, schema_editor):
    TestSetting = apps.get_model('tests', 'TestSetting')
    TestSetting(name="timer").save()
    TestSetting(name="availability_time_range").save()

    QuestionSetting = apps.get_model('tests', 'QuestionSetting')
    QuestionSetting(name="point").save()



class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0007_alter_questionsetting_conflicts_and_more"),
    ]

    operations = [
        migrations.RunPython(create_settings),
    ]
