# Generated by Django 4.1 on 2022-08-19 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0008_auto_20220819_2104"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionpointsetting",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="point",
                to="tests.question",
                verbose_name="Вопрос",
            ),
        ),
        migrations.AlterField(
            model_name="testavailabilitytimerangesetting",
            name="test",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availability_time_range",
                to="tests.test",
                verbose_name="Тест",
            ),
        ),
        migrations.AlterField(
            model_name="testtimersetting",
            name="test",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timer",
                to="tests.test",
                verbose_name="Тест",
            ),
        ),
    ]
